### ISSUE TITLE
Deployment fails with "Login profile size exceeds 32 KiB"

### ISSUE THREAD

**Issue by GeorgianaElena** [2i2c-org/pilot-hubs#206]
The [latest PR merge](https://github.com/2i2c-org/pilot-hubs/runs/1854876784) errored with:
```
INVALID_ARGUMENT: Login profile size exceeds 32 KiB. Delete profile values to make additional space
```

This is probably because every time time the deployment GHA runs, we do a login. This is turn generates a ssh key pair. 
We should probably do what the error instructs(`Delete profile values to make additional space`) to make it work again.

**Comment by GeorgianaElena** [comment]
solved by https://github.com/2i2c-org/pilot-hubs/pull/216 :tada:

**Comment by yuvipanda** [comment]
Unfortunately I had to revert the revert in #217, so this isn't solved.

**Comment by yuvipanda** [comment]
This means we have to do https://github.com/2i2c-org/pilot-hubs/issues/83#issuecomment-716643591 for each new hub again, for now.
